SUPER_CONFIG_PATH: ./configs/default.yaml

AUG_RESIZE_SCALES: [224]
AUG_MAX_SIZE: 224
AUG_RANDOM_RESIZE: [224]

BACKBONE_TYPE: video
DETECTION_DATA_TYPE: video
CKPT_PATH: ./pretrained_models/google/siglip2-base-patch16-224
TEXT_ENCODER_CKPT_PATH: ./pretrained_models/google/siglip2-base-patch16-224

LINES_HEAD_TYPE: default

WEIGHT_DECAY: 1.0e-4
LR_BACKBONE: 5.0e-5
LR_SOCCERNET_GSR_DETECTION: 1.0e-4
LR_LINES_DETECTION: 1.0e-3
LR_KEYPOINTS_DETECTION: 1.0e-4
LR_CAMERA_REGRESSION: 1.0e-4
LR_VIDEO_CAPTION: 1.0e-4
LR_CAPTION_CLASSIFICATION: 1.0e-4
LR_CAPTION_CLASSIFICATION_CLASSIFIER: 2.0e-4

SAVE_CHECKPOINT_PER_EPOCH: 1

BATCH_SIZE: 2
NUM_WORKERS: 2
VIDEO_CAPTION_BATCH_SIZE: 2
VIDEO_CAPTION_NUM_WORKERS: 2
NUM_FRAMES: 30
DATASETS_TO_HEADS:
  SoccerNetGSR_Detection: [SoccerNetGSR_Detection, LinesDetection, KeypointsDetection, CameraRegression]
  VideoCaption: [VideoCaption, CaptionClassification]

VIDEO_CAPTION_DATASETS: ['SoccerReplay-1988', 'MatchTime', 'SoccerNet-v2']
LOAD_CHECKPOINTS: True
STAGE_1_CKPT_DIR: ./outputs/video_224_video_detection_all_align/epoch_15

CAPTION_CLASSIFICATION_USE_TRANSFORMERS: True
CAPTION_CLASSIFICATION_NUM_TRANSFORMER_ENCODER: 2
CAPTION_CLASSIFICATION_USE_ATTN_POOL: False
CAPTION_CLASSIFICATION_USE_LAYER_NORM: True
CAPTION_CLASSIFICATION_USE_MLP: False
CAPTION_CLASSIFICATION_DROPOUT_RATE: 0.0