SUPER_CONFIG_PATH: ./configs/default.yaml

DATASETS_TO_HEADS:
  SoccerNetGSR_Detection: [SoccerNetGSR_Detection, LinesDetection, KeypointsDetection, CameraRegression]

ENABLE_SOFTMAX_FOCAL_LOSS: True
LINES_HEAD_TYPE: default