# SoccerTrackerTransformer Configuration

# Import base configuration
imports:
  - base.yaml

# Override specific values
experiment_name: "train_timesformer_100clip_coord_only_not_0init_resume_0init"

model:
  type: SoccerTrackerTransformerTimeSformer
  zero_init_for_residual: false
  zero_init_coord_head_on_resume: true

data:
  dataset_type: "SoccerSequenceCachedDataset"  # Just override the dataset type
  max_clip_frames: 100

training:
  max_iterations: !!int 600 * 1000  # Using YAML's tag to evaluate expression
  
  # Only specify the tasks that differ from base.yaml
  tasks:
    track: false
    role: false
    team: false
    jersey: false
    coord: true
    missing: false 