# SoccerTrackerTransformer Configuration

# Import base configuration
imports:
  - base.yaml

# Override specific values
experiment_name: "train_timesformer_100clip_coord_only_not_0init_startaug_xyflip"

model:
  type: SoccerTrackerTransformerTimeSformer
  zero_init_for_residual: false

data:
  dataset_type: "SoccerSequenceCachedDataset"  # Just override the dataset type
  max_clip_frames: 100
  flip_x_prob: 0.5
  flip_y_prob: 0.5
  use_all_frames_as_start: true

training:
  num_workers: 4

  # Only specify the tasks that differ from base.yaml
  tasks:
    track: false
    role: false
    team: false
    jersey: false
    coord: true
    missing: false 