# SoccerTrackerTransformer Configuration

# Import base configuration
imports:
  - base.yaml

# Override specific values
experiment_name: "train_transformer_100clip_coord_only_not_0init_no_spatial_embed"

model:
  type: SoccerTrackerTransformer
  zero_init_for_residual: false
  use_spatial_embed: false

data:
  dataset_type: "SoccerSequenceCachedDataset"  # Just override the dataset type
  max_clip_frames: 100

training:
  num_workers: 8

  # Only specify the tasks that differ from base.yaml
  tasks:
    track: false
    role: false
    team: false
    jersey: false
    coord: true
    missing: false 