# SoccerTrackerTransformer Configuration

# Import base configuration
imports:
  - base.yaml

# Override specific values
experiment_name: "train_timesformer"

model:
  type: SoccerTrackerTransformerTimeSformer

data:
  dataset_type: "SoccerSequenceCachedDataset"  # Just override the dataset type

training:
  max_iterations: !!int 1000 * 1000  # Using YAML's tag to evaluate expression
  
  # Only specify the tasks that differ from base.yaml
  tasks:
    track: true
    role: true
    team: true
    jersey: false
    coord: true
    missing: false 

  loss_weights:
    track: 100.0     # Track association loss weight
    role: 1.0      # Role classification loss weight
    team: 1.0      # Team classification loss weight
    jersey: 1.0    # Jersey number prediction loss weight
    coord: 1.0     # Coordinate refinement loss weight
    missing: 1.0   # Missing detections prediction loss weight