SUPER_CONFIG_PATH: ./configs/default.yaml

TASKS: [SoccerNetGSR_ReID, SoccerNetGSR_Detection]
DATASETS: [SoccerNetGSR_ReID, SoccerNetGSR_Detection]

BATCH_SIZE: 12
AUG_RESIZE_SCALES: [512]
AUG_MAX_SIZE: 512
AUG_RANDOM_RESIZE: [512]
BACKBONE_TYPE: image
CKPT_PATH: ./pretrained_models/google/siglip2-base-patch16-512
TEXT_ENCODER_CKPT_PATH: ./pretrained_models/google/siglip2-base-patch16-512