SUPER_CONFIG_PATH: ./configs/default.yaml

DATASETS_TO_HEADS:
  # SoccerNetGSR_Detection: [SoccerNetGSR_Detection, LinesDetection, KeypointsDetection, CameraRegression]
  SoccerNetGSR_Detection: [SoccerNetGSR_Detection]

NUM_WORKERS: 24

AUG_RESIZE_SCALES: [224]
AUG_MAX_SIZE: 224
AUG_RANDOM_RESIZE: [224]

BACKBONE_TYPE: image
CKPT_PATH: ./pretrained_models/google/siglip2-base-patch16-224
TEXT_ENCODER_CKPT_PATH: ./pretrained_models/google/siglip2-base-patch16-224

LINES_HEAD_TYPE: default

DETR_ENC_LAYERS: 6
DETR_DEC_LAYERS: 6
DETR_ENABLE_ROLE_CLASSIFICATION: False
DETR_ENABLE_JN_CLASSIFICATION: False
USE_EXTRA_DATA: True
EXTRA_DATA_PATH: ./datasets/SN-GSR-2024/pseudo_pklz/sn500_1000_step3.pklz
EXTRA_DATA_ONLY: True