SUPER_CONFIG_PATH: ./configs/default.yaml

BACKBONE_TYPE: video
DETECTION_DATA_TYPE: video

LINES_HEAD_TYPE: default

LR_BACKBONE: 1.0e-4
LR_SOCCERNET_GSR_DETECTION: 1.0e-4
LR_LINES_DETECTION: 1.0e-3
LR_KEYPOINTS_DETECTION: 1.0e-4
LR_CAMERA_REGRESSION: 1.0e-4
LR_VIDEO_CAPTION: 1.0e-4
LR_CAPTION_CLASSIFICATION: 2.0e-4

SAVE_CHECKPOINT_PER_EPOCH: 1

BATCH_SIZE: 6
NUM_WORKERS: 12
VIDEO_CAPTION_BATCH_SIZE: 6
VIDEO_CAPTION_NUM_WORKERS: 12
NUM_FRAMES: 30
DATASETS_TO_HEADS:
  SoccerNetGSR_Detection: [SoccerNetGSR_Detection, LinesDetection, KeypointsDetection, CameraRegression]
  VideoCaption: [VideoCaption, CaptionClassification]

DETR_HIDDEN_DIM: 512
DETR_ENC_LAYERS: 1
DETR_DEC_LAYERS: 1